# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a27c631fea1b75a874c228d4c964b338d83a7dd4b47c247493ad911868de579569195daeaf106db425590219347256253260e7ed7c3476b08db41cc27fc93a58

test:
  secret_key_base: 371ebda4fdc6539c05ca51762b2869f1db7ab529b099ee4ba67b0a23d285a64ca10e3cbc38ee1b4dfc4c012dd84ee6cab7709d291eeab652b403431eb7ac386d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
